from inc.variables import *
def run():
    print(print_line)
    print(print_exclamation("Attention! This script should be run after you've chrooted into your new system (arch-chroot /mnt /bin/bash)"))
    input(print_message("Press [ENTER] to install your system."))
    print(print_message("Moving file 'locale.gen' to '/etc/locale.gen'"))
    execute("cp files/locale.gen /etc/locale.gen")
    print(print_message("Running 'locale-gen'"))
    execute("locale-gen")
    print(print_message("Adding 'sv_SE.UTF-8' to '/etc/locale.conf'"))
    execute("echo LANG=sv_SE.UTF-8 > /etc/locale.conf")
    print(print_message("Running 'Export LANG=sv_SE.UTF-8'"))
    execute("export LANG=sv_SE.UTF-8")
    print(print_message("Moving file 'vconsole.conf' to '/etc/vconsole'"))
    execute("cp files/vconsole.conf /etc/vconsole.conf")
    print(print_message("Setting zone 'Europe/Stockholm' in '/etc/localtime'"))
    execute("ln -s /usr/share/zoneinfo/Europe/Stockholm /etc/localtime")
    print(print_message("Setting hwclock"))
    execute("hwclock --systohc --utc")
    hostname = input(print_question("Enter your hostname: "))
    execute("echo " + hostname + " > /etc/hostname")
    print(print_message("Making copies of '/hooks/encrypt' and 'install/encrypt'"))
    execute("cp /lib/initcpio/hooks/encrypt{,2}")
    execute("cp /usr/lib/initcpio/install/encrypt{,2}")
    print(print_message("moving file 'encrypt2' to '/lib/initcpio/hooks/encrypt2'"))
    execute("cp files/encrypt2 /lib/initcpio/hooks/encrypt2")
    print(print_message("Moving file 'mkinitcpio.conf' to '/etc/mkinitcpio.conf'"))
    execute("cp files/mkinitcpio.conf /etc/mkinitcpio.conf")
    print(print_message("Running 'pacman -S grub'"))
    execute("pacman -S grub")
    print(print_message("Moving file 'grub' to '/etc/default/grub'"))
    execute("cp files/grub /etc/default/grub")
    print(print_message("Running 'grub-install --recheck /dev/sdb'"))
    execute("grub-install --recheck /dev/sdb")
    print(print_message("grub-mkconfig -o /boot/grub/grub.cfg"))                                                                                  
    execute("grub-mkconfig -o /boot/grub/grub.cfg")
    print(print_message("Runnimg mkinitcpio"))
    execute("mkinitcpio -p linux")
    print(print_message("Copying 'pacman.conf' to '/etc/pacman.conf'"))
    execute("cp files/pacman.conf /etc/pacman.conf")
    print(print_line)
